name: "Start Selenoid Server"
description: "Downloads and starts Selenoid server (Selenium Webdriver compatible) using CM tool"
author: Oleksandr Khotemskyi <xotabu4@gmail.com>
branding:
  icon: "box"
  color: "blue"

inputs:
  version:
    description: "To provide Selenoid version to download"
    required: true
  selenoid-start-arguments:
    description: 'Additional arguments to be added for "./cm selenoid start" command. See full list in readme.md'
    required: false
  args:
    description: "To override Selenoid startup arguments sessions"
    required: false
  browsers:
    description: "Specified browser versions to download"
    required: true
  last-versions:
    description: "Last versions to download"
    required: true
runs:
  using: "node12"
  main: "index.js"
