name: Test Selenoid

on:
  push:
    branches:
      - "*" # matches every branch

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test SELENOID JOB
    steps:
      - uses: actions/checkout@master
      - run: npm ci

      - name: start selenoid
        uses: ./
      - name: is selenoid started?
        run: curl http://localhost:4444/status