name: Test Selenoid

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - name: Start Selenoid
        uses: ./
        with:
          args: -limit 10
          browsers: chrome;firefox
          versions: 1
      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status