name: Test Selenoid

on:
  push:
    branches:
      - "*" # matches every branch

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - name: Start Selenoid
        uses: ./
      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status
